# Generated by Django 3.1.5 on 2021-02-18 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_auto_20210126_1505'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['-created'], 'verbose_name_plural': 'Quizzes'},
        ),
    ]
