# Generated by Django 3.1.7 on 2021-03-03 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0006_auto_20210301_1813"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quiz",
            options={"verbose_name_plural": "Quizzes"},
        ),
    ]
