# Generated by Django 3.1.7 on 2021-03-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0008_question_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="likes",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
